language: pyhton

os:
    - linux

branches:
    only:
    - master

before_install:
    - echo "before_install..."
    - git submodule update --init --recursive
    - git fetch --tags
    - sleep 1
    - git checkout $TRAVIS_BRANCH
    - export PROJECTGITVERSION=`git describe --tags --always |sed 's/^v//'`
    - echo $PROJECTGITVERSION
    - echo $TRAVIS_OS_NAME
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - export TRAVIS_TAG=`git describe --tags --exact-match HEAD 2>/dev/null`
    - echo $TRAVIS_TAG

install:
    - echo "install..."

script:
    - echo "script..."
    - export PACKAGENAME=pulsemodel_$PROJECTGITVERSION.zip
    - echo "Packaging sources of " $PACKAGENAME
    - pwd
    - ls
    - mkdir ../pulsemodel_$PROJECTGITVERSION
    - cp -r * ../pulsemodel_$PROJECTGITVERSION
    - rm -fr ../pulsemodel_$PROJECTGITVERSION/.git*
    - mv ../pulsemodel_$PROJECTGITVERSION .
    - zip -r $PACKAGENAME pulsemodel_$PROJECTGITVERSION
    - ls
    - ls -l $PACKAGENAME

deploy:
  provider: releases
  api_key:
    secure: BlKzFevP0b1d0vB3yfQU4D91agOQ3JA/2mX9gY+rrho0uNlVp+kZIUgPQ4+4EQROwttSdSLMzFLZdAhDmPnS8RP3mBmLdacZ4Z2B27FvhGh+Comfwobk2kT7R2WFg7jAAef9AK3/dJyRYe1bLOEdAGeNlEpa5ucjpLJ389zxKZXkm2T2UMzH+6n+YGND34utB9PKcQ9DluHA9H17FMmxFjQcYCLPiy5ytdOHNUusF9eBoYmgqJnfQ393vWpQbl88HJloPOtdCaCw1XUt6p6AwEsq9F9RP0tDL3hRIXOTk3Uwe1q94wYDR/LFt1MSL/IxQ1PptaszT/CgrHf8y2K+QUKUU2iEIeKywXjYM227+dC8E0VgruMNNWIdOAc6o/e2zJ0ORt8Exh+TYyMWIXIUe4smneLZWjZZVJSO371GWeCgQW4jLh18Ae6CN/FmFiMuhPQDzncoMCr+cJbeQCx3LdYLgaczk5euU5mL6MCJEwYa5Nk2zNKrMrDjx5BQu4cS2zqaGJcKYQ0WPSamDnlgqWFJUW91uscHifKvlkai8kDB8IpsUIRo1aWor9UAJuXPMyJiTT6D2gJxN07ZFmuOBHmGP5FuRSnDwMFN2mHxxbgnnThDu7dmG0bFMFsuCZoSAwezz3yvT15NCm+5a1l3ikZ198Ek6DKzfOLTDL+jbHQ=
  file: $PACKAGENAME
  on:
    repo: gillesdegottex/pulsemodel
